spring.application.name=tarot-site-lab2

# ???????????? ??????????? ?? ??
spring.datasource.url=jdbc:postgresql://localhost:5432/tarot_db
spring.datasource.username=postgres
spring.datasource.password=251723

# ??? Hibernate ??????????? ??????? ???????
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true